import { useState, useEffect } from 'react'
import './App.css'
import { Carousel } from './components/Carousel'
import type { CarouselImage } from './components/Carousel'

// ============ SLIDESHOW CONFIGURATION ============
const SLIDESHOW_CONFIG = {
  // Auto-play interval in milliseconds (1000 = 1 second)
  interval: 2000,

  // Start with auto-play enabled
  autoPlayOnLoad: false,

  // Sort images alphabetically by caption
  sortAlphabetically: true
}
// =================================================

// Convert filename to readable caption (e.g., "bitcoin-coins.jpg" -> "Bitcoin Coins")
function filenameToCaption(filename: string): string {
  return filename
    .replace(/\.(jpg|jpeg|png|gif|webp)$/i, '')
    .split(/[-_]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function App() {
  const [images, setImages] = useState<CarouselImage[]>([])

  // Load image list from manifest (generated by Vite plugin)
  useEffect(() => {
    fetch('/images/manifest.json')
      .then(res => res.json())
      .then((files: string[]) => {
        const loaded = files.map(file => ({
          src: `/images/${file}`,
          alt: filenameToCaption(file),
          caption: filenameToCaption(file)
        }))
        setImages(SLIDESHOW_CONFIG.sortAlphabetically
          ? loaded.sort((a, b) => a.caption.localeCompare(b.caption))
          : loaded
        )
      })
      .catch(() => setImages([]))
  }, [])

  // Show message if no images found
  if (images.length === 0) {
    return (
      <div className="app-container">
        <div className="hero">
          <h1>Bitcoin is Freedom</h1>
          <p className="subtitle">Explore the world of Bitcoin and Lightning Network</p>
        </div>
        <div className="content">
          <section className="info-section">
            <h2>No Images Found</h2>
            <p>
              Add image files (.jpg, .jpeg, .png, .gif, .webp) to the <code>public/images/</code> folder
              to see them in the carousel.
            </p>
          </section>
        </div>
      </div>
    )
  }

  return (
    <div className="app-container">
      <div className="hero">
        <h1>Bitcoin is Freedom</h1>
        <p className="subtitle">Explore the world of Bitcoin and Lightning Network</p>
      </div>

      <Carousel
        images={images}
        interval={SLIDESHOW_CONFIG.interval}
        autoPlayOnLoad={SLIDESHOW_CONFIG.autoPlayOnLoad}
      />

      <div className="content">
        <section className="info-section">
          <h2>About Bitcoin</h2>
          <p>
            Bitcoin is a decentralized digital currency that enables peer-to-peer transactions
            without the need for intermediaries. It represents financial freedom and sovereignty.
          </p>
        </section>

        <section className="info-section">
          <h2>Lightning Network</h2>
          <p>
            The Lightning Network is a second-layer payment protocol that operates on top of
            Bitcoin, enabling fast and low-cost transactions.
          </p>
        </section>
      </div>
    </div>
  )
}

export default App
